### ISSUE TITLE
team.html - CSS cleanup

### ISSUE THREAD

**Issue by alexwuwei** [alexwuwei/Guac-A-Mole-Didactic-Tool#45]
make images fit div and adjust to size. (for img css)

max-width: 100%;
max-height: 100%;  

rounded corners for the div boxes

style header more

**Comment by preetsohal** [comment]
Guys. I am in traffic. I will be there soon. Till then you guys carry on.

Sent from my iPhone

On Jan 26, 2016, at 9:10 AM, Hugo A Guerra <notifications@github.com<mailto:notifications@github.com>> wrote:

make images fit div and adjust to size. (for img css)

max-width: 100%;
max-height: 100%;

rounded corners for the div boxes

style header more

##
